# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myreads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreads',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
