# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-18 15:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myreads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 2, 18, 15, 4, 8, 970579, tzinfo=utc))),
                ('approved_comment', models.BooleanField(default=False)),
                ('gist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myreads.Gist')),
            ],
        ),
    ]
